### PR TITLE
Add member kaori

### PR DESCRIPTION
**Pull request by KaoriOchi**
Revised minor errors in data

### CODE REVIEW

**Comment by Leo-Bol** [comment]
As discussed: Closed - keep one style sheet for now

**Review by Leo-Bol — CHANGES_REQUESTED** [review]
Please keep original style file

**Comment by KaoriOchi** [comment]
The style.css has already been taken down.
This is a pull request for other changes.

**Comment by Leo-Bol** [comment]
Thanks for lettting me know - will approve now

**Comment by KaoriOchi** [comment]
Thanks!

**Pull request merged**
